### PR TITLE
Fix navigation mode to student after add to tutorial

### LINKED ISSUE #129: Adding student to tutorial should not change Navigation Mode
Currently changes to tutorial.

### PR DESCRIPTION
**Pull request by meloppeitreet**
Fixes #129.
Navigation mode remains as STUDENT after adding a student to tutorial.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddStudentToTutorialCommand.java [hunk 1]
```diff
@@ -68,7 +68,7 @@ public CommandResult execute(Model model) throws CommandException {
             model.setStudent(studentToEdit, editedStudent);
         }
 
-        return new CommandResult(MESSAGE_SUCCESS, NavigationMode.TUTORIAL);
+        return new CommandResult(MESSAGE_SUCCESS, NavigationMode.STUDENT);
```
Comment (WhyAre) [inline src/main/java/seedu/address/logic/commands/AddStudentToTutorialCommand.java:71]:
```suggestion
        return new CommandResult(MESSAGE_SUCCESS, NavigationMode.UNCHANGED);
```

I think it would be better if we used `NavigationMode.UNCHANGED` instead

**Review by WhyAre — APPROVED** [review]
